User.create([
  { username: 'root', password: 'password', first_name: 'Americo', last_name: 'Zuzunaga' },
  { username: 'ame.zuz@gmail.com', password: 'password', first_name: 'Americo', last_name: 'Zuzunaga' },
  { username: 'alberto@cyclist.com', password: 'password', first_name: 'Alberto', last_name: 'Contador' },
  { username: 'sean@cyclist.com', password: 'password', first_name: 'Sean', last_name: 'Kelly' },
  { username: 'gino@cyclist.com', password: 'password', first_name: 'Gino', last_name: 'Bartali' },
  { username: 'alfredo@cyclist.com', password: 'password', first_name: 'Alfredo', last_name: 'Binda' },
  { username: 'miguel@cyclist.com', password: 'password', first_name: 'Miguel', last_name: 'Indurain' },
  { username: 'jacque@cyclist.com', password: 'password', first_name: 'Jacque', last_name: 'Anquetil' },
  { username: 'fausto@cyclist.com', password: 'password', first_name: 'Fausto', last_name: 'Coppi' },
  { username: 'bernard@cyclist.com', password: 'password', first_name: 'Bernard', last_name: 'Hinault' },
  { username: 'eddy@cyclist.com', password: 'password', first_name: 'Eddy', last_name: 'Merckx' },
  { username: 'greg@cyclist.com', password: 'password', first_name: 'Greg', last_name: 'LeMond' },
  { username: 'peter@cyclist.com', password: 'password', first_name: 'Peter', last_name: 'Sagan' },
  { username: 'fabiana@cyclist.com', password: 'password', first_name: 'Fabiana', last_name: 'Luperini' },
  { username: 'jeannie@cyclist.com', password: 'password', first_name: 'Jeannie', last_name: 'Longo' },
  { username: 'joane@cyclist.com', password: 'password', first_name: 'Joane', last_name: 'Somarriba' },
  { username: 'maria@cyclist.com', password: 'password', first_name: 'Maria', last_name: 'Canins' },
  { username: 'nicole@cyclist.com', password: 'password', first_name: 'Nicole', last_name: 'Cooke' },
  { username: 'leontinen@cyclist.com', password: 'password', first_name: 'Leontinen', last_name: 'van Moorsel' },
  { username: 'emma@cyclist.com', password: 'password', first_name: 'Emma', last_name: 'Pooley' },
  { username: 'rasa@cyclist.com', password: 'password', first_name: 'Rasa', last_name: 'Polikeviciute' },
  { username: 'marianne@cyclist.com', password: 'password', first_name: 'Marianne', last_name: 'Martin' },
  { username: 'annie@cyclist.com', password: 'password', first_name: 'Annie', last_name: 'Londonderry' },
  { username: 'beryl@cyclist.com', password: 'password', first_name: 'Beryl', last_name: 'Burton' },
  { username: 'mvos@cyclist.com', password: 'password', first_name: 'Marianne', last_name: 'Vos' },
  { username: '@cyclist.com', password: 'password', first_name: '', last_name: '' },
  { username: 'haile@runner.com', password: 'password', first_name: 'Haile', last_name: 'Gebrselassie' },
  { username: 'emil@runner.com', password: 'password', first_name: 'Emil', last_name: 'Zatopek' },
  { username: 'paula@runner.com', password: 'password', first_name: 'Paula', last_name: 'Radcliffe' },
  { username: 'joan@runner.com', password: 'password', first_name: 'Joan', last_name: 'Benoit Samuelson' },
  { username: 'meb@runner.com', password: 'password', first_name: 'Meb', last_name: 'Keflezighi' },
  { username: 'hicham@runner.com', password: 'password', first_name: 'Hicham', last_name: 'El Guerrouj' },
  { username: 'usain@runner.com', password: 'password', first_name: 'Usain', last_name: 'Bolt' },
  { username: 'wilson@runner.com', password: 'password', first_name: 'Wilson', last_name: 'Kipsang Kiprotich' },
  { username: 'florence@runner.com', password: 'password', first_name: 'Florence', last_name: 'Griffith Joyner' },
  { username: 'deena@runner.com', password: 'password', first_name: 'Deena', last_name: 'Kastor' },
  { username: 'geoffrey@runner.com', password: 'password', first_name: 'Geoffrey', last_name: 'Mutai' },
  { username: 'alberto@runner.com', password: 'password', first_name: 'Alberto', last_name: 'Salazar' },
  { username: 'carl@runner.com', password: 'password', first_name: 'Carl', last_name: 'Lewis' },
  { username: 'catherine@runner.com', password: 'password', first_name: 'Catherine', last_name: 'Ndereba' },
  { username: 'kenenisa@runner.com', password: 'password', first_name: 'Kenenisa', last_name: 'Bekele' },
  { username: 'michael@swimmer.com', password: 'password', first_name: 'Michael', last_name: 'Phelps' },
  { username: 'mark@swimmer.com', password: 'password', first_name: 'Mark', last_name: 'Spitz' },
  { username: 'matt@swimmer.com', password: 'password', first_name: 'Matt', last_name: 'Biondi' },
  { username: 'ryan@swimmer.com', password: 'password', first_name: 'Ryan', last_name: 'Lochte' },
  { username: 'gary@swimmer.com', password: 'password', first_name: 'Gary', last_name: 'Hall' },
  { username: 'ian@swimmer.com', password: 'password', first_name: 'Ian', last_name: 'Thorpe' },
  { username: 'aaron@swimmer.com', password: 'password', first_name: 'Aaron', last_name: 'Peirsol' },
  { username: 'nathan@swimmer.com', password: 'password', first_name: 'Nathan', last_name: 'Adrian' },
  { username: 'jenny@swimmer.com', password: 'password', first_name: 'Jenny', last_name: 'Thompson' },
  { username: 'kristin@swimmer.com', password: 'password', first_name: 'Kristin', last_name: 'Otto' },
  { username: 'amy@swimmer.com', password: 'password', first_name: 'Amy', last_name: 'Van Dyken' },
  { username: 'krisztina@swimmer.com', password: 'password', first_name: 'Krisztina', last_name: 'Egerszegi' },
  { username: 'dana@swimmer.com', password: 'password', first_name: 'Dana', last_name: 'Vollmer' },
  { username: 'katie@swimmer.com', password: 'password', first_name: 'Katie', last_name: 'Ledecky' },
  { username: 'dara@swimmer.com', password: 'password', first_name: 'Dara', last_name: 'Torres' },
  { username: 'jennifer@tri.com', password: 'password', first_name: 'Jennifer', last_name: 'Beals' },
  { username: 'jarrod@tri.com', password: 'password', first_name: 'Jarrod', last_name: 'Shoemaker' },
  { username: 'laura@tri.com', password: 'password', first_name: 'Laura', last_name: 'Bennet' },
  { username: 'richard@tri.com', password: 'password', first_name: 'Richard', last_name: 'Varga' },
  { username: 'ryan@tri.com', password: 'password', first_name: 'Ryan', last_name: 'Sissons' },
  { username: 'stuart@tri.com', password: 'password', first_name: 'Stuart', last_name: 'Hayes' },
  { username: 'dave@tri.com', password: 'password', first_name: 'Dave', last_name: 'Scott' },
  { username: 'christiane@tri.com', password: 'password', first_name: 'Christiane', last_name: 'Pilz' },
  { username: 'natascha@tri.com', password: 'password', first_name: 'Natascha', last_name: 'Badman' },
  { username: 'scott@tri.com', password: 'password', first_name: 'Scott', last_name: 'Molina' },
  { username: 'lisa@tri.com', password: 'password', first_name: 'Lisa', last_name: 'Bentley' },
  { username: 'jessica@tri.com', password: 'password', first_name: 'Jessica', last_name: 'Harrison' },
  { username: 'kate@tri.com', password: 'password', first_name: 'Kate', last_name: 'McIlroy' },
  { username: 'yuliya@tri.com', password: 'password', first_name: 'Yuliya', last_name: 'Yelistratova' },
  { username: 'annamaria@tri.com', password: 'password', first_name: 'Annamaria', last_name: 'Mazzetti' },
  { username: 'gwen@tri.com', password: 'password', first_name: 'Gwen', last_name: 'Jorgesen' },
  { username: 'paula@tri.com', password: 'password', first_name: 'Paula', last_name: 'Findlay' },
  { username: 'lucy@tri.com', password: 'password', first_name: 'Lucy', last_name: 'Hall' },
])
