json.extract! route, :id,
              :title,
              :description,
              :author_id,
              :polyline,
              :image_url,
              :big_image_url,
              :distance,
              :elevation,
              :duration,
              :sport,
              :created_at
