json.extract! route, :id,
                     :title,
                     :description,
                     :author_id,
                     :polyline,
                     :image_url,
                     :distance,
                     :elevation,
                     :duration,
                     :created_at
